### ISSUE TITLE
--parse-no-codeind inverted?

### ISSUE THREAD

**Issue by mtklr** [kristapsdz/lowdown#28] opened 2020-07-11 11:50 UTC
Hi,

I happen to have a file with some indentation that lowdown treats as code blocks, even with `--parse-no-codeind. Maybe my brain is broken and I'm interpreting this wrong; no-codeind should disable treating indented text as code, but seems to do the opposite?

Thanks for your time and effort,
Matt

Example file:

```
# indented

    $ # indented code
    $ ls -al

# end
```

Output:

```
$ lowdown -Ttree example
LOWDOWN_ROOT
  LOWDOWN_DOC_HEADER
  LOWDOWN_HEADER
    level: 1
    LOWDOWN_NORMAL_TEXT
      data: 8 Bytes: indented
  LOWDOWN_BLOCKCODE
    data: 27 Bytes: $ # indented code\n$ ...
  LOWDOWN_HEADER
    level: 1
    LOWDOWN_NORMAL_TEXT
      data: 3 Bytes: end
  LOWDOWN_DOC_FOOTER
```

```
$ lowdown -Ttree --parse-no-codeind example
LOWDOWN_ROOT
  LOWDOWN_DOC_HEADER
  LOWDOWN_HEADER
    level: 1
    LOWDOWN_NORMAL_TEXT
      data: 8 Bytes: indented
  LOWDOWN_BLOCKCODE
    data: 27 Bytes: $ # indented code\n$ ...
  LOWDOWN_HEADER
    level: 1
    LOWDOWN_NORMAL_TEXT
      data: 3 Bytes: end
  LOWDOWN_DOC_FOOTER
```

```
$ lowdown -Ttree --parse-codeind example
LOWDOWN_ROOT
  LOWDOWN_DOC_HEADER
  LOWDOWN_HEADER
    level: 1
    LOWDOWN_NORMAL_TEXT
      data: 8 Bytes: indented
  LOWDOWN_PARAGRAPH
    lines: 2, blank-after: 1
    LOWDOWN_NORMAL_TEXT
      data: 21 Bytes:     $ # indented cod...
    LOWDOWN_NORMAL_TEXT
      data: 13 Bytes: \n    $ ls -al
  LOWDOWN_HEADER
    level: 1
    LOWDOWN_NORMAL_TEXT
      data: 3 Bytes: end
  LOWDOWN_DOC_FOOTER
```

**Comment by kristapsdz** [comment] 2020-07-11 12:06
You're correct, the logic is inverted!  Parsing of indented code is the default (i.e., `LOWDOWN_NOCONDEIND` is not set by default), but in main.c:

```
{ "parse-codeindent",   no_argument, &aiflag, LOWDOWN_NOCODEIND },
{ "parse-no-codeindent",no_argument, &riflag, LOWDOWN_NOCODEIND },
```

So specifying `--parse-codeindent` (the documentation is wrong, by the way, it should be `codeindent` and not `codeind`, however `getopt_long()` allows through unique prefixes, so it happens to work) in fact disables code indentation.  Confusing!  These weird negative options are holdovers from the original hoedown source code.  Thanks for the note---I'll get a fix in soon.

**Comment by mtklr** [comment] 2020-07-11 12:21
Thanks very much! :)

**Comment by kristapsdz** [comment] 2020-07-11 13:02
I just submitted a fix for this.  Can you check out HEAD and see if it fixes your problem?  If so, I'll close out a new relesae.

**Comment by mtklr** [comment] 2020-07-11 15:40
Hi,

That seems to fix it.

I'm noticing a couple of other minor similar inconsistencies, should I add them here or create seperate issues? They involved output of indent vs. fenced, and the `-d` and `-e` options (not in manpage) not recognizing `codeind`.

thanks again,
matt

**Comment by kristapsdz** [comment] 2020-07-11 18:23
The `-e` and friends option styles aren't supported any more.  If you have any issues that pertain to the double-dash options, either opening a new issue or mentioning here will do!

**Comment by mtklr** [comment] 2020-07-12 18:33
The only other thing I had was output seems different with `--parse-no-fenced` versus `--parse-no-codeindent`. `fenced` still uses a "codespan" even when disabled - perhaps a screenshot better explains it:

![codeindent-v-fenced](https://user-images.githubusercontent.com/4858543/87253859-94217280-c44c-11ea-999e-1421310d43e6.png)

That's all I have (for now) - thanks!

**Comment by kristapsdz** [comment] 2020-07-23 13:33
That seems to be expected behaviour, or at least traditional behaviour: the back-tick is interpreted to mean the opening of a code section.  Thank you for this report!  I'll close out a release with it.

**Closed by kristapsdz** 2020-07-23 13:33 UTC
