### ISSUE TITLE
Tables longer than one page produce error

### ISSUE THREAD

**Issue by zaimai** [kristapsdz/lowdown#65] opened 2021-03-28 10:39 UTC
Hi,

I noticed that lowdown does not seem to support tables that are longer than one page:

```sh
$ cat <<-EOF | lowdown -sTms | pdfroff -itk -mspdf > table.pdf
app|quality
---|---
lowdown|rocks
lowdown|rocks
lowdown|rocks
lowdown|rocks
lowdown|rocks
lowdown|rocks
lowdown|rocks
lowdown|rocks
lowdown|rocks
lowdown|rocks
lowdown|rocks
lowdown|rocks
lowdown|rocks
lowdown|rocks
lowdown|rocks
lowdown|rocks
lowdown|rocks
lowdown|rocks
lowdown|rocks
lowdown|rocks
lowdown|rocks
lowdown|rocks
lowdown|rocks
lowdown|rocks
lowdown|rocks
lowdown|rocks
lowdown|rocks
lowdown|rocks
lowdown|rocks
lowdown|rocks
lowdown|rocks
lowdown|rocks
lowdown|rocks
lowdown|rocks
lowdown|rocks
lowdown|rocks
lowdown|rocks
lowdown|rocks
lowdown|rocks
lowdown|rocks
lowdown|rocks
lowdown|rocks
lowdown|rocks
lowdown|rocks
lowdown|rocks
lowdown|rocks
lowdown|rocks
lowdown|rocks
lowdown|rocks
lowdown|rocks
EOF

error: page 2: table will not fit on one page; use .TS H/.TH with a supporting macro package 
```
If I understand correctly this could be easily fixed if lowdown would enclose the table header in _.TS H / .TH_ macros, according to `man groff_ms`:

> .TS [H] and .TE
>             Denote a table to be processed by the tbl preprocessor.
>             The optional H argument instructs groff to create a
>             running header with the information up to the TH macro.
>             groff prints the header at the beginning of the table; if
>             the table runs onto another page, groff prints the header
>             on the next page as well.

https://www.man7.org/linux/man-pages/man7/groff_ms.7.html

Thank you for the great work!

**Comment by kristapsdz** [comment] 2021-03-28 11:36
Thank you for reporting this!  Please check if the attached fixes this problem for you (it does for me) and close the issue if it does.  I'll roll a release soon after.

As the commit message says, the fix only works for groff's **-ms**, as **-man** doesn't support the multi-page table syntax.  So this doesn't affect **mandoc** because it doesn't support **-ms** at all.

**Comment by zamai2** [comment] 2021-03-28 12:22
@kristapsdz 

Thank you for this ultrafast response! I can confirm that the fix works. 
Unfortunately I can not close this issue as I lost access the original reporting account.

**Closed** 2021-05-07 08:28 UTC
